version: '3.9'
services:
  ea-main:
    container_name: easy_alphabet_container
    image: yelpinger/easy-alphabet:1.1.4
    restart: always
    ports:
      - '431:8080'
    environment:
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_FILE_NAME: /logs/ea_main/ea-main.log
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE: 5MB
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY: 5
      LOGGING_LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP: 20MB
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/changelog-master.xml
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/ea_main_db
      SPRING_DATASOURCE_USERNAME: ea_admin
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL_ENABLED: false
      SPRING_JPA_OPEN_IN_VIEW_ENABLED: false
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      EA_CONTENT_SUBJECT_SIZE: 250
      EA_CONTENT_OFFSET_PERCENTAGE: 0.1
    volumes:
      - ./docker_data/logs/ea_main:/logs/ea_main
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ea_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ea_main_db
      POSTGRES_HOST: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ea_admin" ]
      interval: 20s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 5m
        max-file: '5'
    volumes:
      - ./docker_data/ea_main_pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@easyalphabet.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5050:80'
