version: '3.9'
services:
  ea-main:
    container_name: easy_alphabet_container
    build: ./
    restart: always
    ports:
      - '8080:8080'
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ea_main_db
      POSTGRES_HOST: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: '10'
    volumes:
      - ./docker_data/microservices_pgdata:/var/lib/postgresql/data